# Programación básica en Python

### Importar librerías 

In [1]:
import numpy as np
#import pandas as pd

## Creación de listas y vectores + operaciones super básicas 

Creación de una lista

In [2]:
#Se define la lista
lista=[-2,5,1,5,3,0,-6.5]

Veamos que pasa al sumar un valor a la lista y al vector

In [3]:
lista+1

TypeError: can only concatenate list (not "int") to list

Como podemos observar se generó un error ya que al ser lista no permite hacer operaciones matemáticas de manera rápida, ya que por definición una lista puede contener mas listas

In [4]:
lista_especial=[-2,5,1,5,3,0,-6.5,[-2,5,1,5,3,0,-6.5],["Receso"]]

In [5]:
print(lista_especial)
print(lista_especial[0])
print(lista_especial[7])
print(lista_especial[7][2])
print(lista_especial[8])

[-2, 5, 1, 5, 3, 0, -6.5, [-2, 5, 1, 5, 3, 0, -6.5], ['Receso']]
-2
[-2, 5, 1, 5, 3, 0, -6.5]
1
['Receso']


Creación de vector a partir de una lista definida

In [6]:
# Convvertimos la lista a vector, lo cual nos ayudará a poder realizar operaciones de manera facil
lista_0=np.array(lista)

In [7]:
print("Lista convertido a vector")
print(lista_0)
print("\n")
print("las operaciones se ejecutan a cada elemento del vector")
print("\n")
print(lista_0+1)
print(lista_0+lista_0)
print(lista_0*lista_0)
print(lista_0/lista_0)

Lista convertido a vector
[-2.   5.   1.   5.   3.   0.  -6.5]


las operaciones se ejecutan a cada elemento del vector


[-1.   6.   2.   6.   4.   1.  -5.5]
[ -4.  10.   2.  10.   6.   0. -13.]
[ 4.   25.    1.   25.    9.    0.   42.25]
[ 1.  1.  1.  1.  1. nan  1.]


C:\Users\Omar\anaconda3\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: invalid value encountered in true_divide
  if __name__ == '__main__':


Podemos ver un **warning** debido a que en la división, uno de los elementos es cero

**Creación de vector a partir de numero aleatorios**

https://numpy.org/doc/1.16/reference/routines.random.html

In [8]:
#random.rand(): vector con elementos aleatorios
lista_1=np.random.rand(8)
lista_2=lista_1+1
print(lista_1)
print(lista_2)

[0.95475934 0.88093363 0.07340492 0.47615909 0.09590056 0.80049001
 0.77790843 0.5286604 ]
[1.95475934 1.88093363 1.07340492 1.47615909 1.09590056 1.80049001
 1.77790843 1.5286604 ]


In [9]:
#random.randint: genera numero aleatorio entre dos números.
lista_3=np.random.randint(2,18)
print(lista_3)

3


In [10]:
#random.randn: genera vector de distribución normal
lista_4=np.random.randn(10)
print(lista_4)

[-1.63793751 -1.02995994 -0.47723705 -0.6198172  -0.51422968 -1.17304574
 -0.32534812  1.15245358  1.48656872 -2.22271192]


**Operaciones aritmeticas de los elementos de un vector**

In [10]:
print("suma de los elementos del vector")
print(lista_1.sum())
print("\n")
print("promedio de los elementos del vector")
print(lista_1.mean())
print("\n")
print("mediana de los elementos del vector")
print(np.median(lista_1))

suma de los elementos del vector
4.588216378637088


promedio de los elementos del vector
0.573527047329636


mediana de los elementos del vector
0.6532844172426486


**Subconjunto de un vector**

In [11]:
lista_6=np.random.random(50)
print(lista_6.shape)
lista_6_1=lista_6[10:20]
print(lista_6_1.shape)

(50,)
(10,)


### Vectores de cero y unos

Se usa la función "zeros" para generar un vector de "n" elementos 0.

In [12]:
vector_0=np.zeros(10)
vector_0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Se usa la función "ones" para generar un vector de "n" elementos 1.

In [13]:
vector_1=np.ones(10)
vector_1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### Matrices

Matriz de ceros

In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

Matriz desde una lista

In [15]:
lista_7=[["a",1,"#"],[1,-3,"b"]]
np.array(lista_7)

array([['a', '1', '#'],
       ['1', '-3', 'b']], dtype='<U2')

In [16]:
np.array(lista_7*3)

array([['a', '1', '#'],
       ['1', '-3', 'b'],
       ['a', '1', '#'],
       ['1', '-3', 'b'],
       ['a', '1', '#'],
       ['1', '-3', 'b']], dtype='<U2')

In [17]:
lista_8=[[3,5,6],[2,4,3]]
Matriz_2=np.array(lista_8)
print(Matriz_2)

[[3 5 6]
 [2 4 3]]


Modificar los elementos de una matriz

In [18]:
print("cambiar el elemento (0,2) por cero")
Matriz_2[0,2]=0
print(Matriz_2)

cambiar el elemento (0,2) por cero
[[3 5 0]
 [2 4 3]]


In [19]:
print("multiplicar la columna del medio por -3")
Matriz_2[:,1]=Matriz_2[:,1]*(-3)
print(Matriz_2)

multiplicar la columna del medio por -3
[[  3 -15   0]
 [  2 -12   3]]


### Concatenación

In [20]:
a="Sacaré"
b=20
c="en el curso"

#como b es numerico hay que convertir a string
print(a+" "+ str(b) + " " + c)

Sacaré 20 en el curso


### Operadores lógicos

Pueden revisar el siguiente enlace o muchos más que hay en la web
https://j2logo.com/python/tutorial/operadores-en-python/

Revisemos los más usados

In [21]:
#definimos variables
z=10
x=8
y=3
w=15

#Veamos resultados
print("x es mayor que z")
print(x>z)
print("\n")
print("x es mayor que z o x es mayor que y")
print(x>z or x>y)
print("\n")
print("z es mayor o igual que y y z es diferente a w")
print(z>=y and z!=w)

x es mayor que z
False


x es mayor que z o x es mayor que y
True


z es mayor o igual que y y z es diferente a w
True


### Operadores aritméticos 

In [22]:
print('Operador potencia "**"')
print("elevar x a la w: ",end="")
print(x**w)
print("\n")
print('Operador modulo "%"')
print("modulo de z entre y: ",end="")
print(z%y)
print("\n")
print('Operador cociente "//"')
print("cociente de z entre y: ",end="")
print(z//y)

z=10
x=8
y=3
w=15


Operador potencia "**"
elevar x a la w: 35184372088832


Operador modulo "%"
modulo de z entre y: 1


Operador cociente "//"
cociente de z entre y: 3


## Sentencia if, else 

https://j2logo.com/python/tutorial/python-if-sentencia/

De manera general la estructura del comnando if es la siguiente:

In [ ]:
if condicion:
    bloque que se ejcuta

Recordar que hay que respetar la tabulación en python.

##### else/ elif 

In [ ]:
if condicion_1:
    bloque_1
elif condicion_2:
    bloque_2
else:
    bloque 3

Algunos ejemplos:

1. Calcular la división de 2 números (x/y)

In [23]:
x=2
y=6

In [24]:
if y != 0 :
    print("la división de " + str(x) + "/" + str(y) + " es igual a: ", end="")
    print(np.round(x/y,2))
else:
    print("y toma el valor de cero; por tanto, no se puede calcular")

la división de 2/6 es igual a: 0.33


Notemos que usamos la función "np.round()" de numpy

Vamos aprovechar la condicional de if/else para definir como se crea una función simple en python

### Bonus

https://entrenamiento-python-basico.readthedocs.io/es/latest/leccion5/funciones.html

In [25]:
def division_facil(x,y):
    if y != 0 :
        print("la división de " + str(x) + "/" + str(y) + " es igual a: ", end="")
        print(np.round(x/y,2))
    else:
        print("y toma el valor de cero; por tanto, no se puede calcular")

In [26]:
division_facil(2,0)

y toma el valor de cero; por tanto, no se puede calcular


In [27]:
division_facil(8,6)

la división de 8/6 es igual a: 1.33


¿Funciones con excepciones?

In [28]:
def division_facil_2(x,y):
    try:
        print("la división de " + str(x) + "/" + str(y) + " es igual a: ", end="")
        print(np.round(x/y,2))
    except:
        return "No se puede calcular"

###### ¿Si necesito que el valor sea ingresado en el notebook?

Se usa la función "input" para que guarde el valor que se vaya a escribir

In [29]:
x = float(input("Ingresar el primer número: "))
y = float(input("Ingresar el segundo número: "))
division_facil_2(x,y)

Ingresar el primer número: 6
Ingresar el segundo número: 0
la división de 6.0/0.0 es igual a: 

'No se puede calcular'

### Fin Bonus 

## Bucles 

### For 

https://j2logo.com/bucle-for-en-python/

Usado para recorrer lista, vectores, matrices y demás. Sintáxis:

In [ ]:
for <elemento> in <vector,rango>:
    bloque código

Ejemplo 2:

Imprimir cada elemento de la lista de un vector.

In [30]:
lista_8=np.random.random(10)
for i in lista_8:
    print(np.round(i,2))

0.63
0.58
0.71
0.5
0.47
0.52
0.78
0.44
0.59
0.36


Ejemplo 3:

Imprimir los valores de un vector multiplicado por el tamaño del mismo

In [31]:
tamanio=len(lista_8)
for i in lista_8:
    print(np.round(i*tamanio,2))

6.28
5.76
7.11
4.98
4.75
5.22
7.78
4.42
5.9
3.58


Ejemplo 4:

Imprimir los valores hasta que encuentre un número menor 0.5

In [32]:
lista_8

array([0.62808635, 0.57586581, 0.71109688, 0.49796184, 0.47460598,
       0.52206285, 0.77766184, 0.44154541, 0.59002065, 0.35783299])

In [34]:
for i in lista_8:
    if i<0.5:
        break
    print(np.round(i,2))        

0.63
0.58
0.71


Ejemplo 5:

Guardar en un vector 15 números aleatorios entre 3 y 20 mediante un for

In [35]:
#Creamos un vector vacío
Vector_2=[]
for i in range(15):
    num_random=np.random.uniform(3,20)
    Vector_2.append(np.round(num_random,5))
# para numero aleatorios enteros, usar la función np.random.randint()    

In [36]:
Vector_2

[14.57393,
 18.9478,
 18.06328,
 16.83876,
 6.0632,
 12.86989,
 5.71032,
 9.92751,
 16.69473,
 8.65869,
 4.6011,
 6.0591,
 10.7085,
 13.21212,
 6.37228]

### While 

https://j2logo.com/python/tutorial/python-while-bucle/

Usado para resolver los bloques de código mientras se cumpla la condición. Sintáxis:

In [ ]:
while condicion:
    bloque

In [37]:
#Recordar: para extraer un elemento del vector, según la posición se usa de la siguiente manera:
print("primer elemento")
print(Vector_2[0])
print("\n")
print("sexto elemento")
print(Vector_2[5])

primer elemento
14.57393


sexto elemento
12.86989


Ejemplo 6:

Separar en dos vectores considerando un mumero de corte

In [38]:
indice=0
tamanio=len(Vector_2)

vector_menor_10=[]
vector_10_a_mas=[]

while indice<tamanio:
    num_corte=Vector_2[indice]    
    if num_corte<10:
        vector_menor_10.append(num_corte)
        indice +=1
    else:
        vector_10_a_mas.append(num_corte)
        indice +=1

print("Vector original")        
print(Vector_2)
print("\n")
print("Vector con elementos menores a 10")
print(vector_menor_10)
print("\n")
print("Vector con elementos mayores o igual a 10")
print(vector_10_a_mas)

Vector original
[14.57393, 18.9478, 18.06328, 16.83876, 6.0632, 12.86989, 5.71032, 9.92751, 16.69473, 8.65869, 4.6011, 6.0591, 10.7085, 13.21212, 6.37228]


Vector con elementos menores a 10
[6.0632, 5.71032, 9.92751, 8.65869, 4.6011, 6.0591, 6.37228]


Vector con elementos mayores o igual a 10
[14.57393, 18.9478, 18.06328, 16.83876, 12.86989, 16.69473, 10.7085, 13.21212]


Haciendo punto de corte dinámico:

In [39]:
indice=0
tamanio=len(Vector_2)
a=float(input("Ingresar el punto de corte: "))

vector_menor_10=[]
vector_10_a_mas=[]

while indice<tamanio:
    num_corte=Vector_2[indice]    
    if num_corte<a:
        vector_menor_10.append(num_corte)
        indice +=1
    else:
        vector_10_a_mas.append(num_corte)
        indice +=1

print("Vector original")        
print(Vector_2)
print("\n")
print("Vector con elementos menores a 10")
print(vector_menor_10)
print("\n")
print("Vector con elementos mayores o igual a 10")
print(vector_10_a_mas)

Ingresar el punto de corte: 8
Vector original
[14.57393, 18.9478, 18.06328, 16.83876, 6.0632, 12.86989, 5.71032, 9.92751, 16.69473, 8.65869, 4.6011, 6.0591, 10.7085, 13.21212, 6.37228]


Vector con elementos menores a 10
[6.0632, 5.71032, 4.6011, 6.0591, 6.37228]


Vector con elementos mayores o igual a 10
[14.57393, 18.9478, 18.06328, 16.83876, 12.86989, 9.92751, 16.69473, 8.65869, 10.7085, 13.21212]


Ejemplo 7:

Revisar stock de frutas (forzamos usar while)

In [40]:
frutas={'Platano':2,'Manzana':5,'Durazno':3,'Papaya':0,'Mandarina':0,'Naranja':5}

In [41]:
frutas

{'Platano': 2,
 'Manzana': 5,
 'Durazno': 3,
 'Papaya': 0,
 'Mandarina': 0,
 'Naranja': 5}

In [42]:
indice=0
tamanio=len(frutas)
while indice<tamanio:
    for i,j in frutas.items():
        if j>0:
            print(i," ",j)
        else:
            print(i, " Agotado")
        indice +=1

Platano   2
Manzana   5
Durazno   3
Papaya  Agotado
Mandarina  Agotado
Naranja   5


In [43]:
frutas.values()

dict_values([2, 5, 3, 0, 0, 5])

### Ejercicios 

1. Hacer calculadrora básica, ingresando dos números y la operación a realizar.

2. guardar en un vector los números pares multiplicados por 5 de un vector de tamaño 100 creado de manera aleatoria (tienen que ser naturales).
2.1. ¿De que tamaño es el vector generado por los numeros pares?
2.2. ¿ Cuanto suman los elementos del vector?
2.3. imprimir vector*

3. adivinar el numero que se genera al azar (randint) del 1 al 20. Si es menor que imprima que esta por debajo, si es mayor que está por arriba y si es el número "adivinaste!". Se de be ingresar el numero de manera dinámica y debe tener 3 oportunidades. *

4.Mediante un ejemplo mostrar las diferencias entre break y continue en un for anidado.*